### ISSUE TITLE
FYI: I think by now there are more such switches

### ISSUE THREAD

**Issue by assarbad** [KiFilterFiberContext/warbird-obfuscator#1]
You can consult [my YAML over here](https://github.com/assarbad/msvc-undoc/blob/main/msvc.yaml). I found the following in MSVC toolset 14.34.31933, `link.exe` 14.34.31937.0 (38f375b084e796c6be3ae724641136897770fbc4858e578724f7956c41c48fce):

- **`/wbrdcfg`**
- **`/wbrddll`**
- **`/wbrdlog`**
- `/wbrdreporterrors`
- **`/wbrdschema`**
- `/wbrdsummary`
- `/wbrdtestencrypt`

Those in bold are mentioned in your README.

Btw: thanks for sharing your research!

**Comment by KiFilterFiberContext** [comment]
The flags have been added to the README. 
Thanks for the help!
